server:
  port: 8989

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/xuan_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: zyx
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
knife4j:
  enable: true
blog:
  txcos:
    tmpSecretId: ${blog.txcos.tmpSecretId} # 你的secretId
    tmpSecretKey: ${blog.txcos.tmpSecretKey} # 你的secretKey
    bucketName: ${blog.txcos.bucketName} # 你的bucketName
    region: ${blog.txcos.region} # 你仓库的地址
