server:
  port: 7777
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/xuan_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: zyx
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除的字段
      logic-delete-field: delFlag
      # 代表已删除的值
      logic-delete-value: 1
      # 代表未删除的值
      logic-not-delete-value: 0
      # 主键自增策略，以mysql数据库为准
      id-type: auto
knife4j:
  enable: true
servlet:
  multipart:
    max-request-size: 1024MB
    max-file-size: 1024MB
blog:
  txcos:
    tmpSecretId: ${blog.txcos.tmpSecretId} # 你的secretId
    tmpSecretKey: ${blog.txcos.tmpSecretKey} # 你的secretKey
    bucketName: ${blog.txcos.bucketName} # 你的bucketName
    region: ${blog.txcos.region} # 你仓库的地址
  log:
    enable: ${blog.log.enable} # 是否开启日志
    path: ${blog.log.path} # 日志路径